version: '3.9'

services:
  web:
#    build: ./test_3_project
    build:
      context: ./test_3_project
      dockerfile: Dockerfile.prod
    command: gunicorn test_3_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  pgdbdata: