version: '3.9'

services:
  web:
#    build: -./test_3_project
    build:
      dockerfile: ./test_3_project/Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
#    command:
#      - "python"
#      - "manage.py"
#      - "runserver"
#      - "0.0.0.0:8000"
    command:
      - gunicorn
      - wsgi:application
      - --bind
      - "0.0.0.0:8000"
    volumes:
      - ./test_3_project:/usr/src/app/
#    volumes:
#      - .:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - pgdb
    env_file:
      - ./.env.dev
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_3_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=55660078aA
      # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/


volumes:
  pgdbdata:
