version: '3.9'

services:
  app:
    build:
      context: ./test_3_project
      dockerfile: Dockerfile
#    command:
#      - "python"
#      - "manage.py"
#      - "runserver"
#      - "0.0.0.0:8000"
    command:
      - gunicorn
      - test_3_project.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    volumes:
      - ./test_3_project:/app
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - pgdb
    env_file:
      - ./.env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"


  pgdb:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata:
